### ISSUE TITLE
How to use node mailer

### ISSUE THREAD

**Issue by wimpywarlord** [whoanuragverma/backend-1#1]
We at VinnovateIT reviewed your project. 

Here are some humble suggestions and some guidance.

We expected the emailing to be sent inhouse.

One way this could be achieved, Is using node mailer.

Here is a tutorial about the same. 

Link: https://github.com/whoanuragverma/backend-1

Good work and best of luck.

**Comment by whoanuragverma** [comment]
Hi, 
Seems like there has been some problem as I'm already sending an email and the tutorial links also points to my repository.

Please clarify.

**Comment by wimpywarlord** [comment]
Let me cross-verify once again.

**Comment by wimpywarlord** [comment]
I am not receiving any emails, checked my spam as well as. Why don't we have a call, and you show me its inner workings.

**Comment by whoanuragverma** [comment]
Actual email sending would need Gmail OAuth, which I intentionally didn't add because that would be insecure for my account as I will need to publish those credentials on GitHub.

For that reason I'm using ethreal.email which is great for testing nodemailer. The emails you send via ethreal are never delivered rather are captured and stored temporarily on their server.

You can visit [ethreal.email](https://ethereal.email/) using the following credentials and see your emails there:
Email: kiel25@ethereal.email
Password: rHJQg9dj95cuf8RkmM

You can see your email there. This information is also mentioned on the create meeting page. Please verify again.

**Comment by wimpywarlord** [comment]
Ho alright. I was unaware of ethreal, its also mentioned in the official documentation of node mailer. Learnt something new today.

Great thank you for the clarification, also my apologies. 

We have reviewed your submission, best of luck.
